//
//  RingmeOttSdk.h
//  RingmeOttSdk
//
//  Created by Ringme on 09/09/2022.
//

#import <Foundation/Foundation.h>

#import "XMPPFramework.h"
#import "XMPPAttentionModule.h"
#import "XMPPCapabilitiesCoreDataStorage.h"
#import "XMPPRoomCoreDataStorage.h"
#import "XMPPMessage+XEP_0066.h"
#import "XMPPMessageArchiving_Message_CoreDataObject.h"
#import "DDLog.h"
#import "XMPPMessage+XEP_0085.h"
#import "XMPPRoomMessageHybridCoreDataStorageObject.h"
#import "XMPPvCardAvatarCoreDataStorageObject.h"
#import "XMPPvCardTemp.h"
#import "XMPPRosterCoreDataStorage.h"
#import "XMPPvCardTempModule.h"
#import "XMPPvCardTempEmail.h"
#import "XMPPIQ+XEP_0060.h"
#import "XMPPMessageArchivingCoreDataStorage.h"
#import "XMPPUser.h"
#import "XMPPIQ+LastActivity.h"
#import "XMPPLastActivity.h"
#import "XMPPMessage+XEP_0172.h"
#import "NSXMLElement+XEP_0297.h"
#import "XMPPMessageArchiving.h"
#import "XMPPRoomHybridStorage.h"
#import "XMPPvCardTempLabel.h"
#import "XMPPCapsCoreDataStorageObject.h"
#import "NSString+XEP_0106.h"
#import "NSString+DDXML.h"
#import "XMPPvCardTempAdr.h"
#import "DDMultiFormatter.h"
#import "XMPPStreamManagementMemoryStorage.h"
#import "XMPPRoomOccupantCoreDataStorageObject.h"
#import "XMPPOutgoingFileTransfer.h"
#import "XMPPCoreDataStorage.h"
#import "XMPPRoomOccupantHybridMemoryStorageObject.h"
#import "DDXMLPrivate.h"
#import "XMPPvCardCoreDataStorageObject.h"
#import "DDAbstractDatabaseLogger.h"
#import "XMPPvCardCoreDataStorage.h"
#import "XMPPIQ+JabberRPCResonse.h"
#import "NSData+XMPP.h"
#import "XMPPvCardAvatarModule.h"
#import "XMPPIQ+JabberRPC.h"
#import "XMPPJabberRPCModule.h"
#import "XMPPRoomMessageCoreDataStorageObject.h"
#import "stringprep.h"
#import "XMPPConstants.h"
#import "RFImageToDataTransformer.h"
#import "XMPPRoomHybridStorageProtected.h"
#import "XMPPBandwidthMonitor.h"
#import "DDList.h"
#import "XMPPRegistration.h"
#import "TURNSocket.h"
#import "XMPPRoster.h"
#import "XMPPGroupCoreDataStorageObject.h"
#import "DDFileLogger.h"
#import "XMPPResourceMemoryStorageObject.h"
#import "XMPPResource.h"
#import "XMPPStreamManagementStanzas.h"
#import "XEP_0223.h"
#import "XMPPCapsResourceCoreDataStorageObject.h"
#import "XMPPURI.h"
#import "NSXMLElement+XEP_0203.h"
#import "XMPPTime.h"
#import "XMPPMessageDeliveryReceipts.h"
#import "XMPPMessage+XEP_0224.h"
#import "XMPPPubSub.h"
#import "DDContextFilterLogFormatter.h"
#import "XMPPGoogleSharedStatus.h"
#import "XMPPRosterMemoryStorage.h"
#import "XMPPAutoTime.h"
#import "XMPPResourceCoreDataStorageObject.h"
#import "XMPPLogging.h"
#import "XMPPStringPrep.h"
#import "XMPPMUC.h"
#import "DDTTYLogger.h"
#import "XMPPDateTimeProfiles.h"
#import "XMPPCoreDataStorageProtected.h"
#import "XMPPRoom.h"
#import "DDDispatchQueueLogFormatter.h"
#import "XMPPParser.h"
#import "XMPPvCardTempTel.h"
#import "DDLog+LOGV.h"
#import "XMPPIQ+XEP_0066.h"
#import "NSXMLElement+XEP_0059.h"
#import "XMPPBlocking.h"
#import "XMPPvCardTempAdrTypes.h"
#import "XMPPTransports.h"
#import "XMPPSoftwareVersion.h"
#import "XMPPMessageArchiving_Contact_CoreDataObject.h"
#import "idn-int.h"
#import "XMPPIncomingFileTransfer.h"
#import "XMPPMessage+XEP_0308.h"
#import "XMPPTimer.h"
#import "XMPPUserMemoryStorageObject.h"
#import "XMPPPrivacy.h"
#import "XMPPCapabilities.h"
#import "XMPPResultSet.h"
#import "XMPPvCardTempBase.h"
#import "XMPPProcessOne.h"
#import "XMPPFileTransfer.h"
#import "XMPPMessageCarbons.h"
#import "XMPPMessage+XEP_0280.h"
#import "XMPPInternal.h"
#import "XMPPPresence+XEP_0172.h"
#import "XMPPMessage+XEP_0184.h"
#import "XMPPSRVResolver.h"
#import "NSDate+XMPPDateTimeProfiles.h"
#import "XMPPStreamManagement.h"
#import "XMPPMessage+XEP0045.h"
#import "XMPPRoomOccupantMemoryStorageObject.h"
#import "XMPPRoomMessage.h"
#import "NSNumber+XMPP.h"
#import "XMPPUserCoreDataStorageObject.h"
#import "XMPPvCardTempCoreDataStorageObject.h"
#import "XMPPMessage+XEP_0333.h"
#import "XMPPRoomPrivate.h"
#import "XMPPRosterPrivate.h"
#import "XMPPRoomOccupant.h"
#import "XMPPRosterMemoryStoragePrivate.h"
#import "XMPPRoomMemoryStorage.h"
#import "DDASLLogger.h"
#import "XMPPXOAuth2Google.h"
#import "NSXMLElement+XEP_0335.h"
#import "XMPPRoomMessageMemoryStorageObject.h"
#import "CarbonTabSwipeNavigation.h"
#import "DDXMLDocument.h"
#import "DDXMLNode+CDATA.h"
#import "grdb_config.h"

//! Project version number for RingmeOttSdk.
FOUNDATION_EXPORT double RingmeOttSdkVersionNumber;

//! Project version string for RingmeOttSdk.
FOUNDATION_EXPORT const unsigned char RingmeOttSdkVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <RingmeOttSdk/PublicHeader.h>


